base:
  project: MLOps
  random_state: 20
  target_col: charges

data_source:
  raw_dataset_csv: data/raw/insurance.csv

load_data:
  clean_data: D:\MLOps Workshop\data\processed\insurance_processed.csv

split_data:
  train_data: D:\MLOps Workshop\data\processed\train_insurance_processed.csv
  test_data: D:\MLOps Workshop\data\processed\test_insurance_processed.csv
  test_size: 0.2

estimator:
  ElasticNet: 
    params:
      alpha: 0.9
      L1_ration: 0.6

model_path : models/models.joblib

reports:
  params: reports/params.json
  score: reports/scores.json