base:
  project: MLOps
  random_state: 20
  target_col: charges

data_source:
  raw_dataset_csv: data/raw/insurance.csv

load_data:
  clean_data: D:\MLOps Workshop\data\processed\insurance_processed.csv

split_data:
  train_data: D:\MLOps Workshop\data\processed\train_insurance.csv
  test_data: D:\MLOps Workshop\data\processed\test_insurance.csv
  test_size: 0.2

estimator:
  ElasticNet:
    params:
      alpha: 0.9
      l1_ratio: 0.1

model_path : models/models.joblib

# reports:
#   params: reports/params.json
#   score: reports/scores.json


mlflow:
  artifact_dir : artifats
  experiment_name : insurance_mlops
  run_name : mlops
  registered_model_name : ElasticNet
  remote_server_uri : http://127.0.0.1:5000