channels:
- conda-forge
dependencies:
- python=3.11.9
- pip<=25.0
- pip:
  - mlflow==2.20.1
  - cloudpickle==3.1.1
  - numpy==1.23.5
  - pandas==2.2.3
  - psutil==6.0.0
  - scikit-learn==1.6.0
  - scipy==1.14.1
name: mlflow-env
